### PR TITLE
Support for optional dependencies in pyproject

### PR DESCRIPTION
**Pull request by ilpianista**
Should help fixing aquasecurity/trivy#3720

### CODE REVIEW

**Comment by ilpianista** [comment]
> Thanks for your contribution! Could you keep the existing test as is and add a new test for this case? Then, we can make sure it works with both string and object.

Well, I didn't remove the existing dependencies (which are in the form `<name>:<string>`), thus this should guarantee that it works with both types. Or am I missing anything?

**Comment by DmitriyLewen** [comment]
Hello @ilpianista 
Thanks for your work!

i found 1 more case - dependency is array(https://github.com/python-poetry/poetry/blob/3e32a4f83e89b2b2bede68e0d375a70931b04a8e/pyproject.toml#L80-L84)
can you also add this case in test?

**Comment by ilpianista** [comment]
@DmitriyLewen done.

**Comment by knqyf263** [comment]
>Well, I didn't remove the existing dependencies (which are in the form <name>:<string>), thus this should guarantee that it works with both types. Or am I missing anything?

It is ok, then. Thanks!

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
