### PR TITLE
refactor(go/binary): use debug/buildinfo to find dependencies

### PR DESCRIPTION
**Pull request by ebati**
I am not sure if we have an API compatibility promise but i didn't remove error definitions to keep the compatibility. If you would like to keep the current version i can add it for version < go1.18

### CODE REVIEW

**Comment by knqyf263** [comment]
Thanks for your contribution! Could you sign our CLA? Also, the test seems to be failing.

**Comment by ebati** [comment]
I signed the CLA.

I removed the current version of binary parsing which lead to failing test (which used go version 1.17). For now i just updated CI to use go version 1.18.

**Review by knqyf263 — APPROVED** [review]
Amazing!

**Comment by knqyf263** [comment]
Thank you so much! Looks perfect!

**Pull request merged**
